=== ChaikovskiyV/CompletedTask3/sources/schema/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/banks"
        xmlns:tns="http://www.example.org/banks"
        elementFormDefault="qualified">
    <element name="banks">
        <complexType>
            <sequence>
                <element ref="tns:bank" maxOccurs="1000"/>
            </sequence>
        </complexType>
    </element>

    <element name="bank" type="tns:bank" abstract="true"/>
    <element name="state-bank" type="tns:state-bank" substitutionGroup="tns:bank"/>
    <element name="private-bank" type="tns:private-bank" substitutionGroup="tns:bank"/>

    <complexType name="bank">
        <sequence>
            <element name="name" type="tns:bank-name"/>             
            <element name="country" type="tns:country-name"/>
            <element name="deposit" type="tns:Deposit"/>
        </sequence>
        <attribute name="id" type="tns:bank-id" use="required"/>
        <attribute name="rating" type="tns:bank-rating" use="optional" default="10"/>
    </complexType>
    <complexType name="Deposit">
        <sequence>
            <element name="type" type="tns:deposit-type"/>
            <element name="depositor" type="tns:depositor-name"/>
            <element name="account-id" type="tns:deposit-account"/>
            <element name="amount-on-deposit" type="tns:amount-on-deposit"/>
            <element name="profitability" type="tns:deposit-profitability"/>
            <element name="time-constraints" type="gYearMonth"/>
        </sequence>
    </complexType>

    <complexType name="state-bank">
        <complexContent>
            <extension base="tns:bank">
                <sequence>
                    <element name="bank-type" type="tns:state-bank-type"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="private-bank">
        <complexContent>
            <extension base="tns:bank">
                <sequence>
                    <element name="state-share" type="tns:private-bank-state-share"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="private-bank-state-share">
        <restriction base="int">
            <minInclusive value="0"/>
            <maxExclusive value="50"/>
        </restriction>
    </simpleType>

    <simpleType name="state-bank-type">
        <restriction base="string">
            <enumeration value="central"/>
            <enumeration value="commercial"/>
        </restriction>
    </simpleType>
    
    <simpleType name="bank-name">
        <restriction base="string">
            <pattern value="[a-zA-Z\s]{5,}"/>
        </restriction>
    </simpleType>
    
    <simpleType name="country-name">
        <restriction base="string">
            <enumeration value="Belarus"/>
            <enumeration value="Russia"/>
            <enumeration value="Ukraine"/>
            <enumeration value="Poland"/>
            <enumeration value="China"/>
            <enumeration value="USA"/>
        </restriction>
    </simpleType>

    <simpleType name="bank-id">
        <restriction base="ID">
            <pattern value="[\w]+"/>
        </restriction>
    </simpleType>

    <simpleType name="bank-rating">
        <restriction base="int">
            <minInclusive value="1"/>
            <maxInclusive value="10"/>
        </restriction>
    </simpleType>

    <simpleType name="deposit-type">
        <restriction base="string">
            <enumeration value="demand"/>
            <enumeration value="fixed"/>
            <enumeration value="payment"/>
            <enumeration value="accumulation"/>
            <enumeration value="metal"/>
            <enumeration value="saving"/>
        </restriction>
    </simpleType>

    <simpleType name="depositor-name">
        <restriction base="string">
            <pattern value="[A-Z][a-zA-Z\s]{2,}"/>
        </restriction>
    </simpleType>

    <simpleType name="deposit-account">
        <restriction base="string">
            <pattern value="[A-Z]{3}B[\d]{8}"/>
        </restriction>
    </simpleType>

  <simpleType name="deposit-profitability">
      <restriction base="double">
          <minExclusive value="0"/>
          <maxExclusive value="100"/>
      </restriction>
  </simpleType>

    <simpleType name="amount-on-deposit">
        <restriction base="int">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>
</schema>

=== ChaikovskiyV/CompletedTask3/sources/banks.xml
<?xml version="1.0" encoding="UTF-8" ?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.org/banks"
       xsi:schemaLocation="http://www.example.org/banks schema/schema.xsd">

    <state-bank id="b1" rating="5">
        <name>HonestBank</name>
        <country>Belarus</country>
        <deposit>
            <type>fixed</type>
            <depositor>Ivanov</depositor>
            <account-id>BYHB15261296</account-id>
            <amount-on-deposit>1000</amount-on-deposit>
            <profitability>11</profitability>
            <time-constraints>2021-12</time-constraints>
        </deposit>
        <bank-type>commercial</bank-type>
    </state-bank>

    <private-bank rating="8" id="b2">
        <name>BestBank</name>
        <country>Belarus</country>
        <deposit>
            <type>saving</type>
            <depositor>Ivanova</depositor>
            <account-id>BYBB11223344</account-id>
            <amount-on-deposit>1550</amount-on-deposit>
            <profitability>18.6</profitability>
            <time-constraints>2022-08</time-constraints>
        </deposit>
        <state-share>10</state-share>
    </private-bank>

    <state-bank id="b3" rating="7">
        <name>MyBank</name>
        <country>Belarus</country>
        <deposit>
            <type>accumulation</type>
            <depositor>Petrov</depositor>
            <account-id>BYMB15264455</account-id>
            <amount-on-deposit>2000</amount-on-deposit>
            <profitability>8.8</profitability>
            <time-constraints>2023-12</time-constraints>
        </deposit>
        <bank-type>central</bank-type>
    </state-bank>

    <private-bank rating="4" id="b4">
        <name>CentralBank</name>
        <country>Poland</country>
        <deposit>
            <type>demand</type>
            <depositor>Kurlovich</depositor>
            <account-id>POCB11221895</account-id>
            <amount-on-deposit>5000</amount-on-deposit>
            <profitability>7.5</profitability>
            <time-constraints>2022-02</time-constraints>
        </deposit>
        <state-share>30</state-share>
    </private-bank>

    <state-bank id="b5" rating="8">
        <name>PolBank</name>
        <country>Poland</country>
        <deposit>
            <type>payment</type>
            <depositor>Shipok</depositor>
            <account-id>POPB45991296</account-id>
            <amount-on-deposit>1000</amount-on-deposit>
            <profitability>5</profitability>
            <time-constraints>2024-01</time-constraints>
        </deposit>
        <bank-type>commercial</bank-type>
    </state-bank>

    <private-bank id="b6" rating="6">
        <name>ZBank</name>
        <country>Poland</country>
        <deposit>
            <type>metal</type>
            <depositor>Luchok</depositor>
            <account-id>POZB11224255</account-id>
            <amount-on-deposit>150000</amount-on-deposit>
            <profitability>1</profitability>
            <time-constraints>2022-10</time-constraints>
        </deposit>
        <state-share>10</state-share>
    </private-bank>

    <state-bank id="b7" rating="9">
        <name>SaveBank</name>
        <country>Russia</country>
        <deposit>
            <type>saving</type>
            <depositor>Gromov</depositor>
            <account-id>RUSB11399455</account-id>
            <amount-on-deposit>250000</amount-on-deposit>
            <profitability>5</profitability>
            <time-constraints>2023-06</time-constraints>
        </deposit>
        <bank-type>commercial</bank-type>
    </state-bank>

    <private-bank rating="3" id="b8">
        <name>YorBank</name>
        <country>Russia</country>
        <deposit>
            <type>accumulation</type>
            <depositor>Krup</depositor>
            <account-id>RUYB44551895</account-id>
            <amount-on-deposit>50500</amount-on-deposit>
            <profitability>8</profitability>
            <time-constraints>2022-05</time-constraints>
        </deposit>
        <state-share>30</state-share>
    </private-bank>

    <state-bank rating="5" id="b9">
        <name>USBank</name>
        <country>USA</country>
        <deposit>
            <type>payment</type>
            <depositor>Kelp</depositor>
            <account-id>USUB12966677</account-id>
            <amount-on-deposit>100</amount-on-deposit>
            <profitability>0.91</profitability>
            <time-constraints>2024-12</time-constraints>
        </deposit>
        <bank-type>central</bank-type>
    </state-bank>

    <private-bank rating="8" id="b10">
        <name>McDuckBank</name>
        <country>USA</country>
        <deposit>
            <type>saving</type>
            <depositor>McDuck</depositor>
            <account-id>BYHB11223344</account-id>
            <amount-on-deposit>25</amount-on-deposit>
            <profitability>0.8</profitability>
            <time-constraints>2022-08</time-constraints>
        </deposit>
        <state-share>30</state-share>
    </private-bank>

    <state-bank id="b11" rating="4">
        <name>FBIBank</name>
        <country>USA</country>
        <deposit>
            <type>accumulation</type>
            <depositor>Noris</depositor>
            <account-id>USFB15264455</account-id>
            <amount-on-deposit>2000</amount-on-deposit>
            <profitability>0.85</profitability>
            <time-constraints>2023-12</time-constraints>
        </deposit>
        <bank-type>central</bank-type>
    </state-bank>

    <private-bank id="b12" rating="6">
        <name>YourBank</name>
        <country>Ukraine</country>
        <deposit>
            <type>demand</type>
            <depositor>Kurlovich</depositor>
            <account-id>POPB11221895</account-id>
            <amount-on-deposit>5000</amount-on-deposit>
            <profitability>6.55</profitability>
            <time-constraints>2022-02</time-constraints>
        </deposit>
        <state-share>30</state-share>
    </private-bank>

    <state-bank rating="5" id="b13">
        <name>UKBank</name>
        <country>Ukraine</country>
        <deposit>
            <type>payment</type>
            <depositor>Demidov</depositor>
            <account-id>UKUB45991296</account-id>
            <amount-on-deposit>10000</amount-on-deposit>
            <profitability>9.75</profitability>
            <time-constraints>2024-01</time-constraints>
        </deposit>
        <bank-type>commercial</bank-type>
    </state-bank>

    <private-bank id="b14" rating="8">
        <name>LuckyBank</name>
        <country>Ukraine</country>
        <deposit>
            <type>metal</type>
            <depositor>Metelko</depositor>
            <account-id>UKLB11224255</account-id>
            <amount-on-deposit>150000</amount-on-deposit>
            <profitability>10.25</profitability>
            <time-constraints>2022-10</time-constraints>
        </deposit>
        <state-share>10</state-share>
    </private-bank>

    <state-bank id="b15">
        <name>ChuckBank</name>
        <country>China</country>
        <deposit>
            <type>saving</type>
            <depositor>Chuck</depositor>
            <account-id>CHCB11399455</account-id>
            <amount-on-deposit>2500</amount-on-deposit>
            <profitability>3.15</profitability>
            <time-constraints>2023-06</time-constraints>
        </deposit>
        <bank-type>commercial</bank-type>
    </state-bank>

    <private-bank id="b16">
        <name>GekBank</name>
        <country>China</country>
        <deposit>
            <type>accumulation</type>
            <depositor>Gek</depositor>
            <account-id>CHGB44551895</account-id>
            <amount-on-deposit>505</amount-on-deposit>
            <profitability>0.35</profitability>
            <time-constraints>2022-05</time-constraints>
        </deposit>
        <state-share>30</state-share>
    </private-bank>

    <private-bank id="b17">
        <name>RabitBank</name>
        <country>Russia</country>
        <deposit>
            <type>saving</type>
            <depositor>Rabit</depositor>
            <account-id>RURB10101010</account-id>
            <amount-on-deposit>100000</amount-on-deposit>
            <profitability>7.55</profitability>
            <time-constraints>2042-12</time-constraints>
        </deposit>
        <state-share>10</state-share>
    </private-bank>

    <private-bank id="b18">
        <name>RabitBank</name>
        <country>Russia</country>
        <deposit>
            <type>saving</type>
            <depositor>Rabit</depositor>
            <account-id>RURB10101010</account-id>
            <amount-on-deposit>111000</amount-on-deposit>
            <profitability>8.5</profitability>
            <time-constraints>2042-12</time-constraints>
        </deposit>
        <state-share>40</state-share>
    </private-bank>
</banks>

=== ChaikovskiyV/CompletedTask3/sources/bankstest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.org/banks"
       xsi:schemaLocation="http://www.example.org/banks schema/schema.xsd">

    <state-bank id="b1" rating="5">
        <name>HonestBank</name>
        <country>Belarus</country>
        <deposit>
            <type>fixed</type>
            <depositor>Ivanov</depositor>
            <account-id>BYHB15261296</account-id>
            <amount-on-deposit>0</amount-on-deposit>
            <profitability>8.8</profitability>
            <time-constraints>2021-12</time-constraints>
        </deposit>
        <bank-type>commercial</bank-type>
    </state-bank>

    <private-bank rating="8" id="b2">
        <name>HonestBank</name>
        <country>Belarus</country>
        <deposit>
            <type>saving</type>
            <depositor>Ivanov</depositor>
            <account-id>BYHB15261296</account-id>
            <amount-on-deposit>150</amount-on-deposit>
            <profitability>16</profitability>
            <time-constraints>2022-08</time-constraints>
        </deposit>
        <state-share>30</state-share>
    </private-bank>

    <state-bank id="b3" rating="7">
        <name>HonestBank</name>
        <country>Belarus</country>
        <deposit>
            <type>accumulation</type>
            <depositor>Ivanov</depositor>
            <account-id>BYHB15261296</account-id>
            <amount-on-deposit>2000</amount-on-deposit>
            <profitability>10</profitability>
            <time-constraints>2023-12</time-constraints>
        </deposit>
        <bank-type>central</bank-type>
    </state-bank>
</banks>
